"""empty message

Revision ID: 2b7349bf9011
Revises: 1fb7c6da302
Create Date: 2016-09-18 04:32:53.154013

"""

# revision identifiers, used by Alembic.
revision = '2b7349bf9011'
down_revision = '1fb7c6da302'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('updated_ts', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('user', 'created_ts',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'created_ts',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('user', 'updated_ts')
    ### end Alembic commands ###
