"""empty message

Revision ID: c3245ff30145
Revises: ddaa5bba7372
Create Date: 2016-09-18 21:32:49.871735

"""

# revision identifiers, used by Alembic.
revision = 'c3245ff30145'
down_revision = 'ddaa5bba7372'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('player1', sa.Integer(), nullable=False),
    sa.Column('player2', sa.Integer(), nullable=True),
    sa.Column('player1_time', sa.Float(), nullable=True),
    sa.Column('player2_time', sa.Float(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player1'], ['user.id'], ),
    sa.ForeignKeyConstraint(['player2'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    ### end Alembic commands ###
