"""empty message

Revision ID: ddaa5bba7372
Revises: 2b7349bf9011
Create Date: 2016-09-18 04:34:45.226359

"""

# revision identifiers, used by Alembic.
revision = 'ddaa5bba7372'
down_revision = '2b7349bf9011'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('best_time', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'best_time')
    ### end Alembic commands ###
